openapi: 3.0.0
info:
  title: Warehouse & Shipment API
  version: 1.0.0

paths:
  /shipments:
    get:
      summary: Get all shipments
      operationId: getAllShipments
      responses:
        '200':
          description: A list of shipments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shipment'

    post:
      summary: Create a new shipment
      operationId: createShipment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShipmentCreate'
      responses:
        '201':
          description: Shipment created

  /shipments/{id}:
    get:
      summary: Get shipment by ID
      operationId: getShipmentById
      parameters:
        - name: id
          in: path
          required: true
          schema
