name: Sync to Azure Repos

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the full GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Configure git
      - name: Configure Git
        run: |
          git config user.name "GitHub CI"
          git config user.email "ci-bot@example.com"

      # Step 3: Show current remotes and branches (debug)
      - name: Debug Git Info
        run: |
          echo "Current remotes:"
          git remote -v
          echo "Current branches:"
          git branch -a
          echo "Last 5 commits:"
          git log -n 5 --oneline

      # Step 4: Add Azure DevOps remote (without embedding secrets in URL)
      - name: Add Azure Remote
        run: |
          git remote add azure https://dev.azure.com/neoniealplan/MvcAspAzure/_git/MvcAspAzure
          git remote -v

      # Step 5: Push changes to Azure using AZURE_PAT from secrets
      - name: Push to Azure
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          echo "Pushing to Azure..."
          git push https://:${AZURE_PAT}@dev.azure.com/neoniealplan/MvcAspAzure/_git/MvcAspAzure main --force
